# Generated by Django 3.1.7 on 2021-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('persontype', models.CharField(max_length=256)),
                ('child_pic', models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/')),
                ('child_info', models.TextField(null=True)),
                ('contact', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=256)),
                ('foundContact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=256)),
                ('child_pic1', models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/')),
                ('child_pic2', models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/')),
                ('child_pic3', models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/')),
                ('child_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
