# Generated by Django 3.1.7 on 2021-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='child_pic4',
            field=models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/'),
        ),
        migrations.AddField(
            model_name='person',
            name='child_pic5',
            field=models.ImageField(default='MissingPersonApp/pic_folder/None/no-img.jpg', upload_to='MissingPerson/pic_folder/'),
        ),
    ]
