# Generated by Django 3.1.7 on 2021-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0002_auto_20210415_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
